jobs:
  deploy-to-k8s:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Kubernetes
          command: |
            cat \<<EOF | kubectl apply -f -
            apiVersion: v1
            kind: Pod
            metadata:
              name: age-calculator
            spec:
              containers:
              - name: age-calculator
                image: syedsohail746/age-calculator:1
                ports:
                - containerPort: 80
            EOF

